### ISSUE TITLE
Preset temperature jumps when finished rotating the encoder

### ISSUE THREAD

**Issue by phatina** [sfrwmaker/hakko_t12#1]
In fast decrement mode, I set the temperature to lowest value 180C, then the Iron jumps to 173. This happens only when setting temperature down.

**Comment by phatina** [comment]
I tried to follow instructions mentioned [here](https://www.hackster.io/sfrwmaker/soldering-iron-controller-for-hakko-t12-tips-on-arduino-f7a888#toc-calibrate-the-soldering-tip-7); now 180C jumps to 150C. Can you guide me, please?

Maybe I am not seeing a bug, but my iron is *not* properly set.

Thanks.

**Comment by sfrwmaker** [comment]
Hello!

It's fine, you have found right manual.
Can you explain in more details what the issue is?

**Comment by phatina** [comment]
I enter `tip cfg` menu and fire up 200C calibration. Tip reaches approximately 200C, which I verified using a thermocouple. Iron then displays `rdy` on the first line. Then I long press the encoder to leave config. menu. Rotating the encoder I set e.g. temperature 180C, after a second, it jumps to 150C (I suspect, there's something wrong in mapping of the internal 0-1023 value to human readable).

Am I doing something wrong?

Thanks a lot!

**Comment by sfrwmaker** [comment]
Hello!

Now i can understand what the issue is. You must calibrate the soldering tip through all the calibration points. Also, i do recommend to calibrate each point several times. The problem is that the controller tries to build three lines through the calibration points. When your tip 'mapping' is different from the standard one, you can get wrong result.

**Comment by phatina** [comment]
Aha.

So I enter `tip cfg` menu and start at 200C point - here I press the encoder to start heating. Once I see `rdy` message I verify the actual temperature against the one on the display. Then I move to 300C and 400C. When Finished, I do a long press to leave `tip cfg` screen and that's it?

**Comment by sfrwmaker** [comment]
Correct. Also, you can configure these points several times for accuracy.

**Comment by phatina** [comment]
Is it possible to do this only for 200C and 300C points and leave 400C point?

**Comment by phatina** [comment]
OK, I followed your instructions and did calibrate the tip for every temperature (200, 300 and 400C). I still see weird low temperature when set to 180C (152C).

**Comment by sfrwmaker** [comment]
Hello!

I think, you can change the reference temperature values. Look at line #35 os the sketch:
const uint16_t temp_tip[3] = {200, 300, 400};   // Reference temperatures for tip calibration (Celsius)
If you require to correctly setup the 180 degrees, i would recommend to setup 150, 200 and 300 degrees as reference points.
Not sure, the controller can keep 180 degrees correctly because of very low PWM signal duty cycle. I mean in low duty we can face low accuracy. Let's see 5 and 6 are closest values, but the difference is 20%.
It the controller cannot keep the temperature accurately, you can use 12v power supply.

**Comment by phatina** [comment]
Hi,

me personally, I do not need 180C that much. At this point, I can see the jump at most. I set e.g. 185, 190C and after half a second, the temperature on display jumps to 156C or so. This is annoying.

I tried to use older code from git history which does not use calibration at all, but then no tip is recognized.

Do you have any advice?

**Comment by phatina** [comment]
I created a [Pull Request](https://github.com/sfrwmaker/hakko_t12/pull/2) with fix for this. Please review.

**Comment by sfrwmaker** [comment]
New version of firmware uploaded. Please, check it out.

**Comment by phatina** [comment]
Yes, now it works as expected. So I can close my PR... BTW, Please try to be more descriptive in your commits; and also stage changes so that they form a logical change.

Anyway, thanks for being supportive! :+1:
